# Generated by Django 3.2.9 on 2021-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLResultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('body', models.JSONField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('send_status', models.IntegerField(choices=[(0, 'Todo'), (1, 'Doing'), (2, 'Done'), (9, 'Error')])),
            ],
        ),
    ]
