# Generated by Django 3.2.9 on 2021-11-03 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_sql_reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlresultreport',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sqlresultreport',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
