# Generated by Django 3.2.9 on 2022-01-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sql_reporter', '0002_auto_20211103_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlresultreport',
            name='result_status',
            field=models.IntegerField(choices=[(0, 'ok'), (1, 'ng')], default=0),
        ),
        migrations.AlterField(
            model_name='sqlresultreport',
            name='send_status',
            field=models.IntegerField(choices=[(0, 'Todo'), (1, 'Doing'), (2, 'Done'), (9, 'Error')], default=0),
        ),
    ]
